try :
    print(x)
except:
    print("exception happend")